import { Pool } from 'pg';
import crypto from 'crypto';

// Pre-built manifest of filenames (generated by script/build.ts)
const mediaList: { photos: string[]; videos: string[] } = require('./media-list.json');

const GITHUB_BASE = 'https://raw.githubusercontent.com/t4hir9/tahir-photography-portfolio1/main/client/public';

function titleFromFilename(filename: string): string {
  return filename
    .replace(/\.[^.]+$/, '')
    .replace(/[_-]+/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .trim();
}

function verifyAdmin(req: any): boolean {
  return (
    !!process.env.ADMIN_PASSWORD &&
    req.headers['x-admin-password'] === process.env.ADMIN_PASSWORD
  );
}

export default async function handler(req: any, res: any) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, X-Admin-Password');
  if (req.method === 'OPTIONS') return res.status(200).end();

  const pool = new Pool({ connectionString: process.env.DATABASE_URL });

  try {
    // ── DELETE /api/portfolio?id=123 ──────────────────────────────────────────
    if (req.method === 'DELETE') {
      if (!verifyAdmin(req)) return res.status(401).json({ message: 'Unauthorized' });
      const id = parseInt(req.query.id as string, 10);
      if (isNaN(id)) return res.status(400).json({ message: 'Invalid id' });
      await pool.query('DELETE FROM portfolio_items WHERE id = $1', [id]);
      return res.status(204).end();
    }

    // ── POST /api/portfolio ──────────────────────────────────────────────────
    if (req.method === 'POST') {
      if (!verifyAdmin(req)) return res.status(401).json({ message: 'Unauthorized' });
      const { title, type, url, thumbnailUrl, category } = req.body;
      if (!title || !type || !url) {
        return res.status(400).json({ message: 'title, type and url are required' });
      }
      const { rows } = await pool.query(
        'INSERT INTO portfolio_items (title, type, url, thumbnail_url, category) VALUES ($1, $2, $3, $4, $5) RETURNING *',
        [title, type, url, thumbnailUrl ?? null, category ?? null]
      );
      return res.status(201).json(rows[0]);
    }

    // ── GET /api/portfolio ───────────────────────────────────────────────────
    if (req.method !== 'GET') return res.status(405).json({ message: 'Method not allowed' });

    const { rows: [{ count }] } = await pool.query(
      'SELECT COUNT(*) as count FROM portfolio_items'
    );

    if (parseInt(count) === 0) {
      const { photos: photoFiles, videos: videoFiles } = mediaList;
      const firstPhoto = photoFiles[0]
        ? `${GITHUB_BASE}/photos/${photoFiles[0]}`
        : `${GITHUB_BASE}/photos/1.jpg`;

      for (const filename of photoFiles) {
        const url = `${GITHUB_BASE}/photos/${filename}`;
        await pool.query(
          'INSERT INTO portfolio_items (title, type, url, thumbnail_url, category) VALUES ($1, $2, $3, $4, $5)',
          [titleFromFilename(filename), 'photo', url, url, 'Photography']
        );
      }
      for (const filename of videoFiles) {
        const url = `${GITHUB_BASE}/videos/${filename}`;
        await pool.query(
          'INSERT INTO portfolio_items (title, type, url, thumbnail_url, category) VALUES ($1, $2, $3, $4, $5)',
          [titleFromFilename(filename), 'video', url, firstPhoto, 'Videography']
        );
      }
    }

    const { rows } = await pool.query(
      'SELECT * FROM portfolio_items ORDER BY created_at DESC'
    );
    return res.status(200).json(rows);

  } catch (err: any) {
    console.error('Portfolio error:', err);
    return res.status(500).json({ message: 'Internal server error' });
  } finally {
    await pool.end();
  }
}
